#!/bin/bash

if [[ -f ~/mawaqit/docker/data/online_url.txt ]]; then
    url=`cat ~/mawaqit/docker/data/online_url.txt`
fi

wget -q --spider $url

if [ $? -ne 0 ]; then
    url=`cat ~/mawaqit/docker/data/offline_url.txt`
    if [ -z "$url" ]; then
        url=http://mawaqit.local/en/id/1
    fi
fi

chromium-browser --app=$url --start-fullscreen --start-maximized