#!/bin/bash

if [[ -f ~/Desktop/online_site.txt ]]; then
    url=`cat ~/Desktop/online_site.txt`
fi

if [[ -f ~/mawaqit/docker/data/online_url.txt ]]; then
    url=`cat ~/mawaqit/docker/data/online_url.txt`
fi

wget -q --spider $url

if [ $? -ne 0 ]; then
    url=http://mawaqit.local/mosquee
fi

chromium-browser --app=$url --start-fullscreen --start-maximized